---
title: "Michalis Zouvelos's CV"
author: Michalis Zouvelos
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
  sheet_is_publicly_readable:
    value: false
output:
  pagedown::html_resume:    
    css: ['dd_cv.css', 'resume']
    self_contained: true
knit: pagedown::chrome_print 
# uncomment the above line to get pdf knitted file
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(magrittr) # For the pipe
source("cv_printing_functions.r")

# After completing the interactive authentication once the first time running gs4_auth in your console
# Then your credentials are cached and by adding the gs4_auth() command in the rmd it authenticates when knitting
library(googlesheets4)
googlesheets4::gs4_auth()

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1pn4JVjnTxRQS3xTAdtuWgpJKMbh6iGoVeWycmVFM7e8/edit#gid=917338460",  
  pdf_mode = params$pdf_mode,
  sheet_is_publicly_readable = params$sheet_is_publicly_readable
)
CV$entries_data <- CV$entries_data %>% dplyr::filter(in_resume == TRUE)
```

```{r}
# install.packages("devtools")

# Use this installation because the original fails from dependency on icon package
# devtools::install_github('Ash706/datadrivencv')
```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries)
```


Contact & Info {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```



technical skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```


Languages 
--------------------------------------------------------------------------------

- **Greek**:   Native
- **English**: Fluent
- **German**:  Intermediate
- **Dutch**:   Beginner





Main
================================================================================

Michalis Zouvelos {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('industry_positions')
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```





Certifications {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('certifications')
```

Obligations {data-icon=stamp}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('obligations')
```



<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

```{r}
CV %<>% print_links()
```
